INSERT INTO image (id, bytes) VALUES (nextval('image_seq'), 'Joao Ratao.png');


INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Granoturco', ' Il granoturco colorato è ricco di antiossidanti che combattono lo stress ossidativo e proteggono le cellule dai radicali liberi, promuovendo la salute.', 1);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Prezzemolo', 'Un erba aromatica comune utilizzata in molte cucine.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Basilico', 'Foglie verdi aromatiche utilizzate soprattutto nella cucina italiana.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Rosmarino', 'Una pianta aromatica con foglie aghiformi, usata per insaporire.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Fagioli', 'I fagioli sono legumi commestibili di forma generalmente ovale o tondeggiante, di colore variegato dal bianco al nero passando per il verde, il giallo e il rosso. Sono una importante fonte di proteine vegetali, fibre, vitamine e minerali. I fagioli vengono utilizzati in moltissime cucine del mondo, sia freschi che secchi, e sono alla base di numerosi piatti tradizionali come minestre, zuppe, insalate e piatti principali.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Origano', 'Erba mediterranea usata essenzialmente nella cucina italiana.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Maiale', 'La carne di maiale è ottenuta dal suino domestico ed è ampiamente consumata per il suo sapore ricco e la sua versatilità in cucina. È una buona fonte di proteine di alta qualità e contiene vitamine del gruppo B, ferro e zinco. È utilizzata fresca o trasformata in prodotti come salsicce e prosciutto.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Pepe di Caienna', 'Il pepe di Caienna è una spezia molto piccante ottenuta dalla macinazione dei peperoncini secchi della specie Capsicum annuum. Ha un colore rosso brillante e un aroma intenso. È utilizzato per aggiungere piccantezza ai piatti e può essere trovato in forma di polvere o fiocchi. Il pepe di Caienna è noto anche per i suoi potenziali benefici per la salute, tra cui proprietà antiossidanti e capacità di migliorare la circolazione sanguigna.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Brodo di pollo', 'Il brodo di pollo è un liquido aromatico e nutriente ottenuto dalla cottura lenta di ossa di pollo con acqua, verdure e aromi come sedano, carote e cipolle. È utilizzato come base per zuppe, risotti e salse, donando profondità di sapore e arricchendo i piatti con sostanze nutritive come collagene, minerali e vitamine.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Cioccolato Fondente', 'Il cioccolato fondente è un tipo di cioccolato con alto contenuto di cacao e basso contenuto di zucchero e latticini. Ha un gusto ricco e amaro, ed è noto per i suoi benefici per la salute grazie agli antiossidanti e ai flavonoidi presenti nel cacao. È utilizzato in vari dolci e come snack salutare.', null);
INSERT INTO ingredient (id, name, description, image_id) VALUES(nextval('ingredient_seq'), 'Latte di cocco', 'Il latte di cocco è un liquido estratto dalla polpa grattugiata dei cocchi maturi. È bianco e cremoso, con un sapore dolce di cocco. Ricco di grassi saturi e nutrienti come vitamine e minerali, è utilizzato in cucina sia per piatti salati come curry e zuppe, sia per dolci e bevande. Il latte di cocco può essere intero, light o sotto forma di crema, ed è anche un popolare sostituto del latte per vegani e persone intolleranti al lattosio.', null);


INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image_id) VALUES (nextval('users_seq'), 'Joao', 'Ratao', 'joao@example.com', '08-11-1974', 'Architetto', 'La nostra tradizione culinaria è il filo che tiene unita la nostra famiglia: ogni piatto è un ricordo gustoso di tempo trascorso insieme!', 'Ciao, sono Joao Ratao, un architetto portoghese di Lisbona con una passione profonda per la cucina, ereditata da mia nonna. Quando non progetto edifici moderni, mi dedico a cucinare e sperimentare nuove ricette. La cucina è per me un''arte che unisce creatività e precisione, proprio come l''architettura.', null);
INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image_id) VALUES (nextval('users_seq'), 'Alessandra', 'Verdi', 'ale.verdi@example.com', '27-05-1975', 'Avvocato', 'La mia passione per la cucina etnica è come un viaggio senza fine: ogni spezia è una nuova avventura e ogni piatto un mondo da scoprire! ', 'Ciao, mi chiamo Alessandra e vivo a Milano. Nonostante il mio lavoro impegnativo, trovo sempre il tempo per dedicarmi alla mia grande passione: la cucina. Nel fine settimana, sperimento nuove ricette e organizzo cene per amici e familiari. Amo la cucina etnica e esplorare sapori e tecniche da tutto il mondo.', null);
INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image_id) VALUES (nextval('users_seq'), 'Marco', 'Santini', 'marco@example.com', '08-11-1989', 'Ingegnere informatico', 'Un bravo ingegnere informatico sa che il segreto di un buon codice è come quello di una buona baguette: tempo, passione e una giusta dose di lievito madre!', 'Ciao, sono Marco, un ingegnere informatico di Roma. Fuori dall''ufficio, mi rilasso e mi esprimo in cucina, dove sono appassionato di panificazione. Sperimentare con farine e lievitazioni è per me una forma di meditazione e creatività.', null);


INSERT INTO recipe (id, name, description, preparation, image_id, cooke_id) VALUES (nextval('recipe_seq'), 'Cachupa', 'La cachupa è un piatto tradizionale di Capo Verde, uno stufato sostanzioso di mais, fagioli, carne e verdure. Rappresenta l''incontro di diverse influenze culturali dell''arcipelago ed è perfetto da condividere in famiglia o con amici.', 'Metti a bagno il mais secco e i fagioli in acqua fredda separatamente per almeno 12 ore o durante la notte. Scola il mais e i fagioli e mettili in una grande pentola con acqua fresca. Porta a ebollizione e cuoci a fuoco medio-basso finché sono teneri (circa 1-2 ore). In una padella grande, scalda un po'' di olio d''oliva e soffriggi la cipolla e l''aglio fino a doratura. Aggiungi le carni (maiale, manzo e pollo) e rosolale fino a che non siano ben dorate. Aggiungi il chorizo tagliato a rondelle e continua a cuocere per qualche minuto. Aggiungi i pomodori pelati, le foglie di alloro, il sale, il pepe e il peperoncino (se lo usi). Cuoci a fuoco lento per circa 30 minuti, aggiungendo un po'' d''acqua o brodo se necessario. Quando il mais e i fagioli sono cotti, aggiungi le carote, la patata dolce e il cavolo alla pentola. Cuoci fino a quando le verdure sono tenere. Unisci il mix di carne e salsiccia alla pentola con il mais, i fagioli e le verdure. Mescola bene. Cuoci a fuoco lento per altri 30-45 minuti, mescolando di tanto in tanto e aggiungendo acqua o brodo se necessario, fino a quando tutti gli ingredienti sono ben amalgamati e il sapore è intenso. Servi la cachupa calda, accompagnata da riso o pane, se desideri. È un piatto unico sostanzioso che può essere gustato in compagnia.', null, 1);
INSERT INTO recipe (id, name, description, preparation, image_id, cooke_id) VALUES (nextval('recipe_seq'), 'Gumbo', 'Questa zuppa densa e ricca è una miscela deliziosa di gamberi freschi, salsiccia affumicata e il trinity creolo di sedano, peperoni e cipolle. Il segreto del suo sapore intenso risiede nel roux, una base di farina tostata che aggiunge profondità e consistenza al piatto', 'Iniziate preparando il roux: cuocete lentamente la farina in una padella fino a quando non raggiunge un colore nocciola scuro. Aggiungete il trinity creolo al roux e fate soffriggere fino a quando le verdure non diventano tenere. Aggiungete la salsiccia affumicata e continuate a cuocere per alcuni minuti. Versate il brodo di pollo, aggiungete i pomodori a pezzetti e condite con pepe di Caienna, foglie di alloro e timo fresco. Cuocete a fuoco lento per almeno un''ora, aggiungendo i gamberi negli ultimi 5-10 minuti di cottura per evitare che diventino gommosi. Servite il vostro Gumbo ben caldo su un letto di riso bianco, con una spruzzata di cipollotto fresco per un tocco finale autentico.', null, 51);
INSERT INTO recipe (id, name, description, preparation, image_id, cooke_id) VALUES (nextval('recipe_seq'), 'Kari Zourit', 'Il Kari Zourit è un piatto iconico delle Seychelles, dove il tenero polpo viene lentamente cotto con cipolle, pomodori e una varietà di spezie esotiche. La cremosità della noce di cocco si intreccia con il piccante del peperoncino, creando un''esplosione di sapori in ogni boccone.', 'In una pentola capiente, scaldate l''olio vegetale a fuoco medio. Aggiungete le cipolle tritate e cuocete finché non diventano trasparenti. Aggiungete i pomodori tritati alla pentola e cuocete per circa 5 minuti, mescolando di tanto in tanto, finché non diventano una salsa densa. Aggiungete il polpo alla pentola. Aggiungete anche il peperoncino fresco (se usato) e le spezie: polvere di peperoncino, cumino, coriandolo, sale e pepe nero. Mescolate bene per distribuire le spezie uniformemente. Versate il latte di cocco nella pentola e portate a ebollizione. Riducete poi il fuoco e lasciate cuocere a fuoco lento, coperto, per circa 45-60 minuti, finché il polpo non diventa tenero e il sugo si è ristretto e densificato. Assaggiate e aggiustate di sale e pepe se necessario. Servite il Kari Zourit caldo, accompagnato con riso bianco e guarnito con prezzemolo fresco o coriandolo. Questo piatto delizioso e ricco di sapori rappresenta perfettamente la cucina delle Seychelles, offrendo un''esperienza culinaria indimenticabile con il suo mix di spezie esotiche e ingredienti locali freschi.', null, 1);
INSERT INTO recipe (id, name, description, preparation, image_id, cooke_id) VALUES (nextval('recipe_seq'), 'Moka Créole', 'Mokà crèole, ovvero la mattonella creola. Di tutte le incredibili e meravigliose ricette tratte dal libro di Brigitte Grondin, La cuisine réunionnaise, ho scelto questa perché è la più casalinga, quella nel cuore dell’autrice', 'Per la pastorizzazione: Versate i tuorli, dopo averli separati dagli albumi, all’interno di una ciotola a bordi alti; Servendovi delle fruste elettriche o a mano, montate i tuorli con metà della dose di zucchero (60g); In un pentolino, preparate lo sciroppo, unendo il rimanente zucchero all’acqua e ponendolo su un fornello a fuoco medio; Mescolate bene lo sciroppo e, quando avrà raggiunto la temperatura di 121 °C, (dovete utilizzare un termometro da cucina), levatelo dal fuoco e versatelo a filo sul composto di tuorli e zucchero continuando a montare finché il composto non assumerà una consistenza liscia e omogenea. Per la mattonella: Montate il burro con lo zucchero al velo. Aggiungete poco alla volta i tuorli pastorizzati e montate. Aggiungete in ultimo il cioccolato. Amalgamate bene, dovrete avere una crema morbida. In una ciotola bassa e larga mescolate il caffè (freddo) con il rum, vi suggerisco di versare il rum un poco alla volta e di assaggiare secondo il vostro gusto. Immergetevi i biscotti e posizionateli in uno strato su un piatto o vassoio da portata. Distribuite la crema e poi rifinite con il cocco. Preparate un altro strato e così via fino al termine dei biscotti. Dovrete terminare con uno strato di crema e di cocco per finitura. Posizionate la mattonella in frigorifero per almeno 12h. Servite freddo.', null, 101)


-- Cachupa

INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 201, 1, 250);
INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 301, 1, 200);
INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 1, 1, 500);

-- Gumbo

INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 1, 51, 400);
INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 351, 51, 10);
INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 401, 51, 1000);

-- Kari

INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 351, 101, 10);
INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 501, 101, 200);

-- Moka

INSERT INTO recipe_ingredient (id, ingredient_id, recipe_id, quantita) VALUES (nextval('recipe_ingredient_seq'), 451, 151, 100);


-- Inserimento di esempi di post

INSERT INTO post (title, content, image_id, created_at) VALUES('Benvenuti ', ' Cari amici della buona cucina e delle avventure gastronomiche, benvenuti nel mio angolo virtuale dedicato alla magica cucina creola di New Orleans! Qui, viaggeremo insieme attraverso le strade profumate di spezie, gli aromi ricchi di storia e i sapori che fanno battere il cuore di questa città così unica nel suo genere. Che siate appassionati di storia, amanti del cibo o viaggiatori della cucina, questo blog è per voi. Esplorate con me la cucina creola di New Orleans e lasciatevi ispirare dai suoi sapori unici e dalla sua ricca tradizione. Accendete i fornelli, mettetevi comodi e preparatevi per un''avventura culinaria che vi lascerà con il desiderio di tornare per gustare ancora. Benvenuti nella mia cucina creola. Buon appetito!', null, CURRENT_TIMESTAMP);
INSERT INTO post (title, content, image_id, created_at) VALUES('Storia della cucina Creola', 'Oggi ci immergeremo nella vibrante cultura gastronomica di New Orleans, famosa per il suo melting pot di sapori e per le sue vivaci celebrazioni. La cucina creola di New Orleans ha radici profonde che risalgono al periodo coloniale. Nata dalla mescolanza delle culture africana, francese, spagnola e delle popolazioni native americane, la cucina creola si è sviluppata nelle case e nei mercati della città, riflettendo l''ingegnosità e la creatività delle persone che vi abitavano. Durante il periodo coloniale francese e spagnolo, molte famiglie aristocratiche e i proprietari delle piantagioni in Louisiana impiegavano cuochi africani e creoli per preparare pasti che combinavano ingredienti locali con tecniche di cottura sofisticate. Questo ha portato alla creazione di piatti iconici come il Gumbo, il Jambalaya e il Red Beans and Rice, che sono diventati simboli della cultura gastronomica creola.', null, CURRENT_TIMESTAMP);

-- Recensioni sul Gumbo

INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho provato a cucinare il gumbo classico e devo dire che è diventato subito uno dei miei piatti preferiti! Questo stufato della Louisiana, ricco di sapori intensi, è fatto con una base di roux scuro, okra, salsiccia andouille e gamberi. La combinazione di spezie cajun, peperoni, cipolle e sedano crea un aroma irresistibile. Il piatto è sostanzioso e perfetto per le fredde serate invernali. Ho servito il gumbo con riso bianco e tutti hanno adorato. Un must per chi ama la cucina del sud degli Stati Uniti!', 1, 51);
INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho seguito una ricetta di gumbo di pollo e salsiccia ed è stata un''esperienza fantastica. La base di roux marrone scuro dona un sapore tostato che si sposa benissimo con il pollo tenero e la salsiccia andouille affumicata. L''aggiunta di okra e spezie cajun dà al piatto un tocco di autenticità che ricorda i sapori della Louisiana. È un piatto unico, ricco e saporito, perfetto per una cena in famiglia. Servito con un po'' di riso bianco, il gumbo è risultato irresistibile. Consiglio vivamente di provare questa ricetta!', 101, 51);

-- Recensioni sulla Cachupa

INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho provato a fare la cachupa seguendo la ricetta tradizionale capoverdiana ed è stata un successo! Questo stufato ricco di mais, fagioli, carne di maiale, manzo e verdure come carote, patata dolce e cavolo è un''esplosione di sapori. La lenta cottura permette ai sapori di amalgamarsi perfettamente. È un piatto sostanzioso, perfetto per le cene in famiglia o con amici. E il giorno dopo è ancora più buono! Un vero comfort food che consiglio a tutti di provare.', 101, 1);