INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Granoturco', 500, ' Il granoturco colorato è ricco di antiossidanti che combattono lo stress ossidativo e proteggono le cellule dai radicali liberi, promuovendo la salute.', 'mais.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Prezzemolo', 500, 'Un erba aromatica comune utilizzata in molte cucine.', 'prezzemolo.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Basilico', 200, 'Foglie verdi aromatiche utilizzate soprattutto nella cucina italiana.', 'basilico.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Rosmarino', 100, 'Una pianta aromatica con foglie aghiformi, usata per insaporire.', 'rosmarino.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Fagioli', 200, 'I fagioli sono legumi commestibili di forma generalmente ovale o tondeggiante, di colore variegato dal bianco al nero passando per il verde, il giallo e il rosso. Sono una importante fonte di proteine vegetali, fibre, vitamine e minerali. I fagioli vengono utilizzati in moltissime cucine del mondo, sia freschi che secchi, e sono alla base di numerosi piatti tradizionali come minestre, zuppe, insalate e piatti principali.', 'fagioli.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Origano', 50, 'Erba mediterranea usata essenzialmente nella cucina italiana.', 'origano.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Maiale', 200, 'La carne di maiale è ottenuta dal suino domestico ed è ampiamente consumata per il suo sapore ricco e la sua versatilità in cucina. È una buona fonte di proteine di alta qualità e contiene vitamine del gruppo B, ferro e zinco. È utilizzata fresca o trasformata in prodotti come salsicce e prosciutto.', 'maiale.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Pepe di Caienna', 20, 'Il pepe di Caienna è una spezia molto piccante ottenuta dalla macinazione dei peperoncini secchi della specie Capsicum annuum. Ha un colore rosso brillante e un aroma intenso. È utilizzato per aggiungere piccantezza ai piatti e può essere trovato in forma di polvere o fiocchi. Il pepe di Caienna è noto anche per i suoi potenziali benefici per la salute, tra cui proprietà antiossidanti e capacità di migliorare la circolazione sanguigna.', 'pepec.png');
INSERT INTO ingredient (id, name, quantita, description, image) VALUES(nextval('ingredient_seq'), 'Brodo di pollo', 500, 'Il brodo di pollo è un liquido aromatico e nutriente ottenuto dalla cottura lenta di ossa di pollo con acqua, verdure e aromi come sedano, carote e cipolle. È utilizzato come base per zuppe, risotti e salse, donando profondità di sapore e arricchendo i piatti con sostanze nutritive come collagene, minerali e vitamine.', 'brodo.png');


INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image) VALUES (nextval('users_seq'), 'Joao', 'Ratao', 'joao@example.com', '08-11-1974', 'Architetto', 'La nostra tradizione culinaria è il filo che tiene unita la nostra famiglia: ogni piatto è un ricordo gustoso di tempo trascorso insieme!', 'Ciao, sono Joao Ratao, un architetto portoghese di Lisbona con una passione profonda per la cucina, ereditata da mia nonna. Quando non progetto edifici moderni, mi dedico a cucinare e sperimentare nuove ricette. La cucina è per me un''arte che unisce creatività e precisione, proprio come l''architettura.', 'Joao Ratao.png');
INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image) VALUES (nextval('users_seq'), 'Alessandra', 'Verdi', 'ale.verdi@example.com', '27-05-1975', 'Avvocato', 'La mia passione per la cucina etnica è come un viaggio senza fine: ogni spezia è una nuova avventura e ogni piatto un mondo da scoprire! ', 'Ciao, mi chiamo Alessandra e vivo a Milano. Nonostante il mio lavoro impegnativo, trovo sempre il tempo per dedicarmi alla mia grande passione: la cucina. Nel fine settimana, sperimento nuove ricette e organizzo cene per amici e familiari. Amo la cucina etnica e esplorare sapori e tecniche da tutto il mondo.', 'Alessandra Verdi.png');
INSERT INTO users (id, name, surname, email, date_of_birth, job, phrase, biography, image) VALUES (nextval('users_seq'), 'Marco', 'Santini', 'marco@example.com', '08-11-1989', 'Ingegnere informatico', 'Un bravo ingegnere informatico sa che il segreto di un buon codice è come quello di una buona baguette: tempo, passione e una giusta dose di lievito madre!', 'Ciao, sono Marco, un ingegnere informatico di Roma. Fuori dall''ufficio, mi rilasso e mi esprimo in cucina, dove sono appassionato di panificazione. Sperimentare con farine e lievitazioni è per me una forma di meditazione e creatività.', 'Marco Santini.png');

INSERT INTO recipe (id, name, description, preparation, image, cooke_id) VALUES (nextval('recipe_seq'), 'Cachupa', 'La cachupa è un piatto tradizionale di Capo Verde, uno stufato sostanzioso di mais, fagioli, carne e verdure. Rappresenta l''incontro di diverse influenze culturali dell''arcipelago ed è perfetto da condividere in famiglia o con amici.', 'Metti a bagno il mais secco e i fagioli in acqua fredda separatamente per almeno 12 ore o durante la notte. Scola il mais e i fagioli e mettili in una grande pentola con acqua fresca. Porta a ebollizione e cuoci a fuoco medio-basso finché sono teneri (circa 1-2 ore). In una padella grande, scalda un po'' di olio d''oliva e soffriggi la cipolla e l''aglio fino a doratura. Aggiungi le carni (maiale, manzo e pollo) e rosolale fino a che non siano ben dorate. Aggiungi il chorizo tagliato a rondelle e continua a cuocere per qualche minuto. Aggiungi i pomodori pelati, le foglie di alloro, il sale, il pepe e il peperoncino (se lo usi). Cuoci a fuoco lento per circa 30 minuti, aggiungendo un po'' d''acqua o brodo se necessario. Quando il mais e i fagioli sono cotti, aggiungi le carote, la patata dolce e il cavolo alla pentola. Cuoci fino a quando le verdure sono tenere. Unisci il mix di carne e salsiccia alla pentola con il mais, i fagioli e le verdure. Mescola bene. Cuoci a fuoco lento per altri 30-45 minuti, mescolando di tanto in tanto e aggiungendo acqua o brodo se necessario, fino a quando tutti gli ingredienti sono ben amalgamati e il sapore è intenso. Servi la cachupa calda, accompagnata da riso o pane, se desideri. È un piatto unico sostanzioso che può essere gustato in compagnia.', 'Cachupa.png', 1);
INSERT INTO recipe (id, name, description, preparation, image, cooke_id) VALUES (nextval('recipe_seq'), 'Gumbo', 'Questa zuppa densa e ricca è una miscela deliziosa di gamberi freschi, salsiccia affumicata e il trinity creolo di sedano, peperoni e cipolle. Il segreto del suo sapore intenso risiede nel roux, una base di farina tostata che aggiunge profondità e consistenza al piatto', 'Iniziate preparando il roux: cuocete lentamente la farina in una padella fino a quando non raggiunge un colore nocciola scuro. Aggiungete il trinity creolo al roux e fate soffriggere fino a quando le verdure non diventano tenere. Aggiungete la salsiccia affumicata e continuate a cuocere per alcuni minuti. Versate il brodo di pollo, aggiungete i pomodori a pezzetti e condite con pepe di Caienna, foglie di alloro e timo fresco. Cuocete a fuoco lento per almeno un''ora, aggiungendo i gamberi negli ultimi 5-10 minuti di cottura per evitare che diventino gommosi. Servite il vostro Gumbo ben caldo su un letto di riso bianco, con una spruzzata di cipollotto fresco per un tocco finale autentico.', 'gumbo.png', 51);

-- Cachupa

INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (1, 201); 
INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (1, 301);
INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (1, 1); 

-- Gumbo

INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (51, 1); 
INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (51, 351);
INSERT INTO recipe_ingredients (recipes_id, ingredients_id) VALUES (51, 401); 

-- Inserimento di esempi di post

INSERT INTO post (title, content, image, created_at) VALUES('Benvenuti ', ' Cari amici della buona cucina e delle avventure gastronomiche, benvenuti nel mio angolo virtuale dedicato alla magica cucina creola di New Orleans! Qui, viaggeremo insieme attraverso le strade profumate di spezie, gli aromi ricchi di storia e i sapori che fanno battere il cuore di questa città così unica nel suo genere. Che siate appassionati di storia, amanti del cibo o viaggiatori della cucina, questo blog è per voi. Esplorate con me la cucina creola di New Orleans e lasciatevi ispirare dai suoi sapori unici e dalla sua ricca tradizione. Accendete i fornelli, mettetevi comodi e preparatevi per un''avventura culinaria che vi lascerà con il desiderio di tornare per gustare ancora. Benvenuti nella mia cucina creola. Buon appetito!', '1post.png ', CURRENT_TIMESTAMP);
INSERT INTO post (title, content, image, created_at) VALUES('Storia della cucina Creola', 'Oggi ci immergeremo nella vibrante cultura gastronomica di New Orleans, famosa per il suo melting pot di sapori e per le sue vivaci celebrazioni. La cucina creola di New Orleans ha radici profonde che risalgono al periodo coloniale. Nata dalla mescolanza delle culture africana, francese, spagnola e delle popolazioni native americane, la cucina creola si è sviluppata nelle case e nei mercati della città, riflettendo l''ingegnosità e la creatività delle persone che vi abitavano. Durante il periodo coloniale francese e spagnolo, molte famiglie aristocratiche e i proprietari delle piantagioni in Louisiana impiegavano cuochi africani e creoli per preparare pasti che combinavano ingredienti locali con tecniche di cottura sofisticate. Questo ha portato alla creazione di piatti iconici come il Gumbo, il Jambalaya e il Red Beans and Rice, che sono diventati simboli della cultura gastronomica creola.', '2post.png', CURRENT_TIMESTAMP);


INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho provato a cucinare il gumbo classico e devo dire che è diventato subito uno dei miei piatti preferiti! Questo stufato della Louisiana, ricco di sapori intensi, è fatto con una base di roux scuro, okra, salsiccia andouille e gamberi. La combinazione di spezie cajun, peperoni, cipolle e sedano crea un aroma irresistibile. Il piatto è sostanzioso e perfetto per le fredde serate invernali. Ho servito il gumbo con riso bianco e tutti hanno adorato. Un must per chi ama la cucina del sud degli Stati Uniti!', 1, 51);
INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho seguito una ricetta di gumbo di pollo e salsiccia ed è stata un''esperienza fantastica. La base di roux marrone scuro dona un sapore tostato che si sposa benissimo con il pollo tenero e la salsiccia andouille affumicata. L''aggiunta di okra e spezie cajun dà al piatto un tocco di autenticità che ricorda i sapori della Louisiana. È un piatto unico, ricco e saporito, perfetto per una cena in famiglia. Servito con un po'' di riso bianco, il gumbo è risultato irresistibile. Consiglio vivamente di provare questa ricetta!', 101, 51);


INSERT INTO review (id, comment, cooke_id, recipe_id) VALUES (nextval('review_seq'), 'Ho provato a fare la cachupa seguendo la ricetta tradizionale capoverdiana ed è stata un successo! Questo stufato ricco di mais, fagioli, carne di maiale, manzo e verdure come carote, patata dolce e cavolo è un''esplosione di sapori. La lenta cottura permette ai sapori di amalgamarsi perfettamente. È un piatto sostanzioso, perfetto per le cene in famiglia o con amici. E il giorno dopo è ancora più buono! Un vero comfort food che consiglio a tutti di provare.', 101, 1);